development:
  adapter: postgresql
  encoding: unicode
  database: stripe_demo
  pool: 5
  username: postgres123
  password: 12345678
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: stripe_demo_production
  pool: 5
  username: postgres123
  password: 12345678
  host: localhost